export default {
 
  "login": "UdoiGogoi-github12345",
  "id": 73052898,
  "node_id": "MDQ6VXNlcjczMDUyODk4",
  "avatar_url": "https://avatars.githubusercontent.com/u/73052898?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/UdoiGogoi-github12345",
  "html_url": "https://github.com/UdoiGogoi-github12345",
  "followers_url": "https://api.github.com/users/UdoiGogoi-github12345/followers",
  "following_url": "https://api.github.com/users/UdoiGogoi-github12345/following{/other_user}",
  "gists_url": "https://api.github.com/users/UdoiGogoi-github12345/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/UdoiGogoi-github12345/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/UdoiGogoi-github12345/subscriptions",
  "organizations_url": "https://api.github.com/users/UdoiGogoi-github12345/orgs",
  "repos_url": "https://api.github.com/users/UdoiGogoi-github12345/repos",
  "events_url": "https://api.github.com/users/UdoiGogoi-github12345/events{/privacy}",
  "received_events_url": "https://api.github.com/users/UdoiGogoi-github12345/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Udoi Shankar Gogoi",
  "company": null,
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "I am a UG student pursuing B.Tech in Computer Science Engg. from NIT Silchar,India.",
  "twitter_username": null,
  "public_repos": 5,
  "public_gists": 0,
  "followers": 4,
  "following": 2,
  "created_at": "2020-10-18T06:43:32Z",
  "updated_at": "2021-06-03T11:26:31Z",
};
